language: php
php:
  - 5.6
  - 5.5
  - 5.4
services: mongodb
before_script:
  - echo 'extension="mongo.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - bash -c 'while ! exec 6<>/dev/tcp/localhost/27017; do echo "$(date) - still trying to connect to mongo"; sleep 1; done'
script: ./build.php
